remote_theme: rauldipeas/hacker
plugins:
- jekyll-remote-theme
title: APT repository
description:  My personal apt repository
favicon: https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/Papirus/32x32/apps/distributor-logo-debian.svg