name: Repositório APT
on:
  push:
    branches:    
      - 'main'
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash -x env.sh
      - name: Compilação do repositório APT
        run: bash build.sh
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
      - name: Limpeza de logs antigos
        run: bash actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}