name: APT repository
on:
  push:
    branches:    
      - 'main'
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          bash -x env.sh
          bash -x build.sh
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{secrets.EMAIL_SERVER}}
          server_port: ${{secrets.EMAIL_SERVER_PORT}}
          username: ${{secrets.EMAIL_ADDRESS}}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: ${{secrets.EMAIL_ADDRESS}}
          from: GitHub Actions