name: APT repository
on:
  push:
    branches:    
      - 'main'
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: bash -x env.sh
      - name: Build APT repository
        run: bash -x build.sh
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
      - name: Cleanup old logs
        run: bash -x actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}