name: Repositório APT
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash scripts/env.sh
      - name: Compilação do repositório APT
        run: bash scripts/build.sh
        env:
          GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
      - name: Limpeza de logs antigos
        run: bash scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}