# This is a basic workflow to help you get started with Actions

name: APT repository

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo sed -i 's/focal/jammy/g' /etc/apt/sources.list
          sudo add-apt-repository -yn multiverse
          sudo add-apt-repository -yn universe
          echo\
            'deb [arch=all] https://proget.hunterwittenborn.com makedeb main'|\
            sudo tee\
            /etc/apt/sources.list.d/makedeb.list
          wget -qO-\
            'https://proget.hunterwittenborn.com/debian-feeds/makedeb.pub'|\
            sudo gpg --dearmor -o\
            /etc/apt/trusted.gpg.d/makedeb-archive-keyring.gpg\
            >/dev/null
          sudo apt update
          sudo apt install -y makedeb

      # Runs a single command using the runners shell
      - name: Run a one-line script
        #run: echo Hello, world!
        run: bash build.sh
